services:
  parking:
    build:
      context: .
      args:
        - UID=${APP_UID}
        - GID=${APP_GID}
    user: "${APP_UID}:${APP_GID}"
    env_file: .env
    volumes:
      - db_data:/app/src/db

volumes:
  db_data:
