# Generated by Django 6.0.3 on 2026-03-14 08:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Mesečna cena')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datum izmene')),
            ],
            options={
                'verbose_name': 'Podešavanja parkinga',
                'verbose_name_plural': 'Podešavanja parkinga',
            },
        ),
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(editable=False, unique=True, verbose_name='Broj mesta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivno')),
                ('notes', models.TextField(blank=True, verbose_name='Napomena')),
            ],
            options={
                'verbose_name': 'Parking mesto',
                'verbose_name_plural': 'Parking mesta',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ParkingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ime')),
                ('last_name', models.CharField(max_length=50, verbose_name='Prezime')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('plate', models.CharField(max_length=20, unique=True, verbose_name='Registarska oznaka')),
                ('notes', models.TextField(blank=True, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum registracije')),
            ],
            options={
                'verbose_name': 'Korisnik parkinga',
                'verbose_name_plural': 'Korisnici parkinga',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Kreiranje'), ('update', 'Izmena'), ('delete', 'Brisanje'), ('payment', 'Uplata'), ('cancel', 'Otkazivanje')], max_length=20, verbose_name='Akcija')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(verbose_name='Opis')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Vreme')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Izvršio')),
            ],
            options={
                'verbose_name': 'Zapis aktivnosti',
                'verbose_name_plural': 'Zapisi aktivnosti',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Datum početka')),
                ('end_date', models.DateField(blank=True, help_text='Ostavite prazno za automatsko obnavljanje', null=True, verbose_name='Datum isteka')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Automatsko obnavljanje')),
                ('monthly_price', models.DecimalField(blank=True, decimal_places=2, help_text='Ostavite prazno za podrazumevanu cenu', max_digits=8, null=True, verbose_name='Mesečna cena')),
                ('status', models.CharField(choices=[('pending', 'Na čekanju'), ('active', 'Aktivna'), ('expired', 'Istekla'), ('cancelled', 'Otkazana')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum kreiranja')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Datum izmene')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='home.parkingspot', verbose_name='Parking mesto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='home.parkinguser', verbose_name='Korisnik')),
            ],
            options={
                'verbose_name': 'Pretplata',
                'verbose_name_plural': 'Pretplate',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_from', models.DateField(verbose_name='Period od')),
                ('period_to', models.DateField(verbose_name='Period do')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Iznos')),
                ('paid_date', models.DateField(default=django.utils.timezone.now, verbose_name='Datum uplate')),
                ('method', models.CharField(choices=[('cash', 'Gotovina'), ('bank_transfer', 'Prenos'), ('card', 'Kartica'), ('other', 'Ostalo')], default='cash', max_length=20, verbose_name='Način plaćanja')),
                ('note', models.TextField(blank=True, verbose_name='Napomena')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Datum kreiranja')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='home.subscription', verbose_name='Pretplata')),
            ],
            options={
                'verbose_name': 'Uplata',
                'verbose_name_plural': 'Uplate',
                'ordering': ['-paid_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('spot',), name='unique_active_subscription_per_spot'),
        ),
    ]
