# Generated by Django 6.0.3 on 2026-03-14 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='period_from',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='period_to',
        ),
    ]
