# Generated by Django 6.0.3 on 2026-03-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_payment_period_from_remove_payment_period_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkinguser',
            name='plate',
            field=models.CharField(blank=True, max_length=20, verbose_name='Registarska oznaka'),
        ),
    ]
