# Generated by Django 6.0.3 on 2026-04-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_parkinguser_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Broj mesta'),
        ),
    ]
