# Generated by Django 6.0.3 on 2026-04-01 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_parkingspot_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_active_subscription_per_spot',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='status',
        ),
    ]
