# Generated by Django 6.0.3 on 2026-04-06 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_subscription_unique_active_subscription_per_spot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='home.subscription', verbose_name='Pretplata'),
        ),
    ]
