# Generated by Django 6.0.3 on 2026-04-14 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_payment_subscription_payment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='home.parkinguser', verbose_name='Korisnik'),
            preserve_default=False,
        ),
    ]
